---

##
# We try to set as many config values through ENV vars
# See https://docs.impierce.com/unicore/deployment/configuration

##
# The following values are not supported through ENV vars (yet)
display:
  - name: EduBadges
    locale: en
    logo:
      uri: https://www.surf.nl/files/styles/social_media/public/2023-12/edubadges-icoon-met-witruimte-v2_2.png
      alt_text: EduBadges Logo
